### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by llagos** [Fruchtzwerg94/PlantUmlViewer#10]
Hi. Just installed this plugin using Plugin Manager. All ok. Later installed Java, but JAVA_HOME is not set, so I added the path to the bin directory directly. Restarted Npp and now there is an error saying:

Java exec "path" does not exist
Make sure Java can be found by setting the right path in the plugins options

So, do I need to input the "path" or the whole "path\java.exe"?

Env:
win11
npp 8.5.2 64 bits

Thanks,

**Comment by Fruchtzwerg94** [comment]
Hi @llagos ,

you need to set the whole path to the executable. It is also shown in the readme:
![grafik](https://github.com/Fruchtzwerg94/PlantUmlViewer/assets/29866610/7a896188-5d9f-41d4-b0bd-7073a688dfef)
Have fun with the plugin.
