### ISSUE TITLE
[BUG] Plugin breaks npp 8.5.5

### ISSUE THREAD

**Issue by DenoBeno** [Fruchtzwerg94/PlantUmlViewer#13]
**Description**
After installing the plantUML plugin, npp 8.5.5 doesn't start. 

**Reproduction**
1. Install npp 8.5.5
2. install plantUML plugin

**Expected behavior**
After the plugin installation notepad++ doesn't start anymore

**Screenshots**
not applicable. notebook++simply doesn't start at all

**Environment**
 - Windows: 11
 - Notepad++ version: 8.5.5 64-bit

**Additional information**

The problem is related to java path. I was able to resolve it by instaling npp8.5.4. Installing plantUML viewer doesn't break this version of notepad++
After configuring the javapath in plantUML viewer plugin, I was able to upgrade npp to version 8.5.5 (currently the latest one) and everything still works. Hope this helps.

**Comment by Fruchtzwerg94** [comment]
Hi @DenoBeno 

sorry to hear that you are facing some troubles with the plugin and thanks for your very detailed bug report.
I've tried to reproduce your issue by doing the following steps on Win10:

1. Downloaded, extracted and started the [latest version of Notepad++](https://notepad-plus-plus.org/downloads/v8.5.5/) portable
2. Installed the plugin via the Plugin manager
3. Restarted Notepad++

Unfortunately, I was not able to reproduce the issue doing these steps. Could you try to reproduce the issue by doing exactly the following steps on your device as well? Are there other details (everything could be relevant) you may noticed or have in mind?

BR,
Philipp

**Comment by Fruchtzwerg94** [comment]
After investigation of the issue, I was able to track the problem down to an activated safety feature in Notepad++ which mainly impacts Windows 11 devices.

See the following discussions for detailed information and background:

- [Notepad++ Community: Notepad++ v8.5.5 Release](https://community.notepad-plus-plus.org/post/88577)
- [Notepad++ Community: SQLinForm x64 crashes with N++ 8.5.5](https://community.notepad-plus-plus.org/topic/24810/sqlinform-x64-crashes-with-n-8-5-5)

Finally, [this Notepad++ commit](https://github.com/notepad-plus-plus/notepad-plus-plus/commit/c45d7aca75211434651745059647f4c29bac7ec6) was created to fix this issue in further Notepad++ versions.

Thanks @DenoBeno for reporting this problem and your valuable details about it.
