### ISSUE TITLE
Using a local theme file

### ISSUE THREAD

**Issue by GennDALF** [Fruchtzwerg94/PlantUmlViewer#18]
### Description
Plugin throw an error after trying to find a local theme file.

### Reproduction
1. Save theme file named `puml-theme-foo.puml` where `foo` is the name of the theme
2. Add `!theme foo from relative\path\to\theme\folder` command 
3. Click on 'Refresh'

### Expected behavior
Image rendered using referenced local theme file.

### Environment
 - Windows 10 Pro
 - Notepad++ 8.5.3 64-bit
```cmd
> tree /f
_scripts
├───.styles
│       puml-theme-monokai.puml
│       puml-theme-stack_overflow.puml
└───oop
    └───aggregation1.puml
```

### Additional information
The `!theme` command works fine with built-in themes.
The theme file works fine. Tested in 
 - PlantUML Integration plugin for Intellij IDEA 
 - command line use of independent packet plantuml.jar from official site

### Files
![2023-09-19_133422](https://github.com/Fruchtzwerg94/PlantUmlViewer/assets/7238252/6bda81d6-4ac3-4932-8c17-d06b5bab6498)
[puml-theme-monokai.zip](https://github.com/Fruchtzwerg94/PlantUmlViewer/files/12657829/puml-theme-monokai.zip)

**Comment by Fruchtzwerg94** [comment]
Hi @GennDALF ,

thanks for your detailed report. Relative paths where not in my mind and supported yet. I've created an initial fix for it. Please have a look and try out the [latest build](https://github.com/Fruchtzwerg94/PlantUmlViewer/actions/runs/6236396880) and let me know if this works for you.

BR,
Philipp

**Comment by GennDALF** [comment]
Hi @Fruchtzwerg94,

Thanks for the prompt reaction. Last build works clean and perfect – danke sсhön.

![2023-09-19_202354](https://github.com/Fruchtzwerg94/PlantUmlViewer/assets/7238252/4ea1b273-8289-4f7f-8d41-2ba1d4f537c3)

Kind regards,
Gennadiy

**Comment by Fruchtzwerg94** [comment]
Your welcome, thanks for the feedback.
Bitteschön ;-)
