### ISSUE TITLE
Opnening include.puml file doesn't work

### ISSUE THREAD

**Issue by fdahlberg** [Fruchtzwerg94/PlantUmlViewer#26]
**Description**
I'm trying to open an include.puml file generated by https://github.com/pierre3/PlantUmlClassDiagramGenerator

**Reproduction**
create a .net core project and add some classes and interfaces
install PlantUmlClassDiagramGenerator
generate .puml file
Try to open .puml file in notepad using the plantumlviewer plugin.
Get the following error message:
![image](https://github.com/Fruchtzwerg94/PlantUmlViewer/assets/9571179/a9625585-a4a9-4fc3-8993-874829d16113)

**Expected behavior**
I would expect to see a uml diagram...

**Screenshots**
Added above

**Environment**
 - Windows: 11
 - Notepad++ version:  8..6.2 64-bit

**Additional information**
No

**Comment by Fruchtzwerg94** [comment]
Hi @fdahlberg,

looks like something is unusual with your files and includes. Please attach the files you are trying to generate to allow a more detailed investigation.

BR, Philipp

**Comment by Fruchtzwerg94** [comment]
Closing this issue since no detailed information given.
