### ISSUE TITLE
Support customized Java configuration

### ISSUE THREAD

**Issue by Decimaldelimiter** [Fruchtzwerg94/PlantUmlViewer#27]
**Description**
At the moment, it is no way to apply customized Java runtime configuration by call Java based rendering in PlantUmlViewer

**Solution**
Provide additional field(s) in 'PlantUML Viewer options' dialog for set the JVM configuration. Can be done either as a single multiline field or as bundle of fields each one for a common configuration argument. Validate and apply the content before call Java.

**Alternatives**
Opt. 1: read the JVM configuration from an external file like it is implemented by Eclipse in eclipse.ini (problems: need to set the path to the file, need to distribute a template etc.)
Opt. 2: recognize and support the Java start arguments in the existing configuration string 'Java path' in 'PlantUML Viewer options' dialog (simple but is injection risk).

**Comment by Fruchtzwerg94** [comment]
Hi @Decimaldelimiter ,

thanks for you proposal. I am curious what the use case here. Could you give some details about what arguments you want to use and why?

BR, Philipp

**Comment by Decimaldelimiter** [comment]
Sure. My use case is the standard one. In NPP, I add some very simply diagram, like:

<code>[b1]<->[b2]</code>

and then start the refresh in the viewer pane.

The first refresh (including, apparently, some initialization works) takes, in my case, about 6 seconds. 
Each next refresh takes ca 2 seconds.
So _actually_, it is not really an issue but rather an inconvenience.

My first idea for reduce the refresh time (especially, of the first one) is to manipulate, someway, the Java heap size by apply -Xms / -Xmn 
Is the expectation actually right? or you do not expect any improvement this way?

**Comment by Fruchtzwerg94** [comment]
I don't think setting other heap sizes will improve performance in a way you are really going to recognize it here if we are talking of multiple seconds. Anyway, I've did some benchmarks on my device to compare different values for _Xms_ and _Xmn_, the difference in runtime was ... basically nothing. I don't think this differs a lot on other devices, but would't exclude that.

It's just a rough estimation, but could you do some benchmarks on your device using the plain [PlantUML CLI interface](https://plantuml.com/command-line)? What do you see on your device using the defaults and different values for  _Xms_ and _Xmn_?

**Comment by Decimaldelimiter** [comment]
Tja... ¯\_(ツ)_/¯ Yes, you 're right, 
I cannot see no difference between the calls from the GUI and from the command line...

**Comment by Fruchtzwerg94** [comment]
So unfortunately it seems like it would not make sense to bring in this feature here. I am going to close the issue.
BR, Philipp
