### ISSUE TITLE
Document backgroundColor white automatically changed to transparent

### ISSUE THREAD

**Issue by Deab22** [Fruchtzwerg94/PlantUmlViewer#28]
**Description**
When generating a diagram, if its backgroundColor is set to white, the diagram will always have a transparent background

**Reproduction**
1. Write Diagram
---
Example:
```
@startuml

rectangle A
rectangle B

A --> B

@enduml
```
OR
```
@startuml

skinparam backgroundColor white

rectangle A
rectangle B

A --> B

@enduml
```
---
3. Generate Preview / Export PNG / Export SVG

-> The generated diagram has a transparent background

**Expected behavior**
The diagram has a white background
OR
The plugin has an option to toggle "transparent background by default"

**Screenshots**
![PlantUMLBug](https://github.com/Fruchtzwerg94/PlantUmlViewer/assets/88623347/560272b2-0d3c-48d3-80b4-3a07b0a48cac)

**Environment**
 - Windows 10 LTSC
 - Notepad++ version: v8.6.8 (64-bit)
 - Plugin version: v1.7.0.11 (x64)

**Comment by Fruchtzwerg94** [comment]
Hi @Deab22 ,

thanks for your report. I am able to reproduce it. It can be broken down to an update of the underlying SVG.NET library. I have to check some what exactly causes it.

BR, Philipp

**Comment by Fruchtzwerg94** [comment]
It took me some time but in the end, the solution was ridiculously easy. Check out the [latest build](https://github.com/Fruchtzwerg94/PlantUmlViewer/actions/runs/9921911113) which should fix the issue.
Let me know if it fowks for you.

BR, Philipp
