### ISSUE TITLE
Place an png-img to the header leads to "Cannot Decode"

### ISSUE THREAD

**Issue by SieDa** [Fruchtzwerg94/PlantUmlViewer#34]
**Description**
As #30 fixed the !include (support ./ and ../ and the  %dirpath(), %filename() usage in this PlugIn, there are two issues left in that example - might be, they are related somehow: 

**1. the header image**
As shown in #30 code example, if you remove the comment, 
the simple placement of an png-img still leads to the error message: "Cannot Decode",
while this is processed correctly in the git bash command line for the same PlantUML Version. 

**Expected behavior**
```
left header
<img: src="image.png"{scale=0.12}>
end header
```
Should place an img to the header, which is in the same directory as the source file, 
and relative paths should work as well: ./imgage.png or ../img/image.png should work as well. 

Is it possible to specify, that the embedded image can be defined as SVG
and that the output is directly povided in high quality and well readable SVG in any scaling?  

**2. the access to global variables:**
I tried to output the JAVA_HOME global variable - still does not work. 

**Environment**
 - Windows: 10  
 - Notepad++ version: 8.7.1
 - Plug-In 1.8.0.12 (1.2024.8)
 - with comparison to git bash processing in windows linked to 1.2024.8 and working with JAVA_HOME

**Referencing** 
 I recognized some discussions adressing such similar to other plugins / SVG usage,  but can not identify any help from that in N++: 
  - https://github.com/plantuml/plantuml/discussions/1792 
  - https://github.com/plantuml/plantuml/issues/1199

**Comment by SieDa** [comment]
1. if the file is missing - tiny typo - the error message is "Cannot Decode" (sorry). 
2. As in my example in #30 I tried both with and without $ - result is empty: 
```
%getenv("$JAVA_HOME")
%getenv("JAVA_HOME")
%get_variable_value("JAVA_HOME")
%get_variable_value("$JAVA_HOME")
```

While in git bash: echo $JAVA_HOME provides the path to the JRE.

**Comment by Fruchtzwerg94** [comment]
Not really related to the original issue but I've created a fix for it. Please try out the latest build: [11996453450](https://github.com/Fruchtzwerg94/PlantUmlViewer/actions/runs/11996453450)

**Comment by SieDa** [comment]
%getenv("JAVA_HOME") works with that fix - thanks a lot.
