### ISSUE TITLE
Note doesn't render correctly in Plugin (but does at CMD)

### ISSUE THREAD

**Issue by begleysm** [Fruchtzwerg94/PlantUmlViewer#5]
Hello,

I'm new to PlantUML but have jumped in with a pretty giant diagram for my first go.  I've been using Notepad++ with your PlantUML plugin as my primary editing/rendering tool.

For most of my diagram build I have had good success, however as I "got toward the end" weird things started happening.  I think it might have to do with the diagram being too large for something in the plugin?

I can render the diagram correctly at the command line using _plantuml-1.2022.5.jar_ but it does not render correctly (after growing past a certain size) in the PlantUML Viewer Notepad++ plugin.

In this example you'll see that a note tied to both the yellow packages on the far right appears in both the "test_working_" images but only in the CMD version of the "test_not_working_" images.  The "test_not_working.txt" file adds 16 lines that are not in the original.  I've been able to also induce "syntax errors" that aren't really there by adding more lines to the diagram.

I'm running Notepad++ v8.4.2 (64-bit) with PlantUML Viewer 1.1.1.5.

At the command line I'm using _plantuml-1.2022.5.jar_

Both are using Java JRE 1.8.0_331

Take a look at the attachments:
- **test_working.txt** renders correctly in both Notepad++ and at the command line
-- **test_working_NPP.png** was rendered in Notepad++
-- **test_working_CMD.png** was rendered at the command line
- **test_not_working.txt** adds 16 lines (all connections) and only renders correctly at the command line (notice the note that links the two yellow packages on the far right only renders in the CMD variant, not the NPP variant)
-- **test_not_working_NPP.png** was rendered in Notepad++
-- **test_not_working_CMD.png** was rendered at the command line

Thanks,
Sean

[test_working.txt](https://github.com/Fruchtzwerg94/PlantUmlViewer/files/8930870/test_working.txt)
[test_not_working.txt](https://github.com/Fruchtzwerg94/PlantUmlViewer/files/8930871/test_not_working.txt)
![test_working_NPP](https://user-images.githubusercontent.com/1275999/174388768-1d6a4dac-b9d4-4ecf-9e4e-64f0df938924.png)
![test_working_CMD](https://user-images.githubusercontent.com/1275999/174388777-02dc9d65-0126-47e4-b219-34ab510ea4ed.png)
![test_not_working_NPP](https://user-images.githubusercontent.com/1275999/174388789-919860b7-841a-4a0a-832e-3d2543388726.png)
![test_not_working_CMD](https://user-images.githubusercontent.com/1275999/174388804-5c5686bc-b70c-46ea-92a9-31989633a1fb.png)

**Comment by Fruchtzwerg94** [comment]
Hi Sean,

nice to hear you are using the plugin for your work. Thanks for your great investigation and hints here already.
After having a look at your samples, my first guess is that this could be really the size of your diagramm. You are exactly working at the size of 10.000 characters. Version 1.1 indeed contains a bug where exactly here some issues are occuring.
Please have a look at the [Changelog](https://github.com/Fruchtzwerg94/PlantUmlViewer/blob/master/CHANGELOG.md) for version 1.2.0.6: _Fixed crash generating large documents with more than 10000 characters_.
Could you please try to render your diagram with the latest release [1.2.0.6](https://github.com/Fruchtzwerg94/PlantUmlViewer/releases/tag/1.2.0.6) to check if the issue also occurs here? For me it seems to work at least.

Let me know if this fixes it also for you.

Cheers,
Philipp

**Comment by begleysm** [comment]
That appears to have fixed it!  Thanks for the quick response!  What incredibly lucky timing that 1.2.06 came out 6 days ago and addressed my very issue!

I had also noticed that the character count was right around 10,000 which seemed suspicious! hehe


Thanks,
Sean

**Comment by Fruchtzwerg94** [comment]
Happy to hear this. Have fun with the plugin!

BR,
Philipp
