### ISSUE TITLE
Remove zoom on scroll

### ISSUE THREAD

**Issue by thijsvanderkraan** [Fruchtzwerg94/PlantUmlViewer#7]
I often accidentally scroll while the mouse is in the Plant preview area. Scrolling is directly linked to zooming, and zooming in or out does not improve the readability

 would prefer scrolling behaves in the same way as notepad itself,
scroll = vertical scroll
ALT-scroll = horizontal scroll
SHIFT-scroll = zoom

**Comment by Fruchtzwerg94** [comment]
Hi  @thijsvanderkraan ,
thanks for the feedback. Indeed the zoom and scrolling behaviour is not really the common way. The specific proposal you've made looks not very common and also not implemented in Notepad++ for me. I think the following should be the most intuitive / common solution (also in Notepad++ by default):

- zoom Ctrl + mouse wheel
- mouse wheel to scroll vertically
- Shift + mouse wheel horizontally

This is exactly what I've implemented in the latest commit. Please have a look at the latest build, try it out and give some feedback if it works for you:
[Build for c42a80b](https://github.com/Fruchtzwerg94/PlantUmlViewer/actions/runs/3315569050)

**Comment by thijsvanderkraan** [comment]
Dear Philip, 

You are absolutely right, I didn't write it down correctly. With scroll I meant the mouse wheel scroll button and I got the shift  and alt mixed up. I tested c42a80b and it works like a charm, thank you!

Best regards,
Thijs
