### ISSUE TITLE
Exception when trying to show preview

### ISSUE THREAD

**Issue by mmmato** [Fruchtzwerg94/PlantUmlViewer#8]
**Description**
I just installed the plugin and give it a try and it is not possible to get a preview diagram. I upgraded to the latest Java 8 version. The dotnet FW is installed. I also have set the path to java.exe. Please have a look at the exception. It is immediately displayed after clicking refresh on the preview pane.

**Screenshots**

Settings
![image](https://user-images.githubusercontent.com/11443171/221570961-2843d225-7835-4e07-815e-0d317e9270ca.png)

Exception
![image](https://user-images.githubusercontent.com/11443171/221571019-8faa2e1a-cf64-4b08-ba13-932f455caaaf.png)

**Environment**
 - Windows 10 1909
 - Notepad++ version: 8.4.8 64-bit

**Comment by Fruchtzwerg94** [comment]
Hi @mmmato ,
I am not able to reproduce the issue using quite the same setup as you mentioned.
This could be related to some encoding problems / inconsistencies on your system which leads to wrong encoded data to be converted to as SVG image.
To get some more details, I've created a version which creates a temporary file with the data which is converted to the SVG image. If you run the generation with this version, the Windows editor pops up with a file which could give a hint to the issue:
[PlantUmlViewer.zip](https://github.com/Fruchtzwerg94/PlantUmlViewer/files/10842856/PlantUmlViewer.zip)
Would be helpful to get it the output here.

**Comment by mmmato** [comment]
Hi @Fruchtzwerg94,

Thanks for your effort. Please see the generated output below.
The SVG code looks ok to me. I entered it in a free online svg converter and I did get the expected image.

tmp file 1:
[2023-03-01T07:17:30.168] [INFO] ThreadId: 1 ThreadName: main JAVA BRIDGE CONSTRUCTOR.
[2023-03-01T07:17:30.170] [INFO] ThreadId: 1 ThreadName: main os.arch: amd64
[2023-03-01T07:17:30.171] [INFO] ThreadId: 1 ThreadName: main LOADING lib: Microsoft.Flow.RPA.Desktop.UIAutomation.Java.Bridge.Native
[2023-03-01T07:17:30.175] [INFO] ThreadId: 1 ThreadName: main >>> Adding listener.
[2023-03-01T07:17:30.206] [INFO] ThreadId: 27 ThreadName: Thread-4 NamedPipe Server is created
[2023-03-01T07:17:30.209] [INFO] ThreadId: 1 ThreadName: main windows.length: 0
[2023-03-01T07:17:30.209] [INFO] ThreadId: 1 ThreadName: main Java Bridge Initialization completed successfully.
<?xml version="1.0" encoding="UTF-8" standalone="no"?><svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" contentStyleType="text/css" height="124px" preserveAspectRatio="none" style="width:104px;height:124px;background:#FFFFFF;" version="1.1" viewBox="0 0 104 124" width="104px" zoomAndPan="magnify"><defs/><g><line style="stroke:#181818;stroke-width:0.5;stroke-dasharray:5.0,5.0;" x1="24" x2="24" y1="37.6094" y2="87.9609"/><line style="stroke:#181818;stroke-width:0.5;stroke-dasharray:5.0,5.0;" x1="76" x2="76" y1="37.6094" y2="87.9609"/><rect fill="#E2E2F0" height="31.6094" rx="2.5" ry="2.5" style="stroke:#181818;stroke-width:0.5;" width="39" x="5" y="5"/><text fill="#000000" font-family="sans-serif" font-size="14" lengthAdjust="spacing" textLength="25" x="12" y="26.5332">Bob</text><rect fill="#E2E2F0" height="31.6094" rx="2.5" ry="2.5" style="stroke:#181818;stroke-width:0.5;" width="39" x="5" y="86.9609"/><text fill="#000000" font-family="sans-serif" font-size="14" lengthAdjust="spacing" textLength="25" x="12" y="108.4941">Bob</text><rect fill="#E2E2F0" height="31.6094" rx="2.5" ry="2.5" style="stroke:#181818;stroke-width:0.5;" width="44" x="54" y="5"/><text fill="#000000" font-family="sans-serif" font-size="14" lengthAdjust="spacing" textLength="30" x="61" y="26.5332">Alice</text><rect fill="#E2E2F0" height="31.6094" rx="2.5" ry="2.5" style="stroke:#181818;stroke-width:0.5;" width="44" x="54" y="86.9609"/><text fill="#000000" font-family="sans-serif" font-size="14" lengthAdjust="spacing" textLength="30" x="61" y="108.4941">Alice</text><polygon fill="#181818" points="64,65.9609,74,69.9609,64,73.9609,68,69.9609" style="stroke:#181818;stroke-width:1.0;"/><line style="stroke:#181818;stroke-width:1.0;" x1="24.5" x2="70" y1="69.9609" y2="69.9609"/><text fill="#000000" font-family="sans-serif" font-size="13" lengthAdjust="spacing" textLength="27" x="31.5" y="65.1045">hello</text></g></svg>|##|##|<PS>|##|##|
Dll Process Attached
Dll Process Detach

tmp file 2:
|##|##|<PS>|##|##|

**Comment by Fruchtzwerg94** [comment]
Hi @mmmato ,
the output shows some content which should definitively not be there. For me it seems like your JAVA executable prints out some additional things, more concrete all lines except the XML line you where able to convert to an image. This output is unexpected and should not be there by default.

Since this is related to your system, I can't answer what exactly leads to the behaviour. Maybe the following links are helpful, I found a few discussions about some hooked DLLs especially related to Power Automate.
- [Stop javax.swing.JOptionPane from printing log to the output](https://stackoverflow.com/questions/71515701/stop-javax-swing-joptionpane-from-printing-log-to-the-output)](https://stackoverflow.com/questions/71515701/stop-javax-swing-joptionpane-from-printing-log-to-the-output)
- [PowerAutomate uninstall problem](https://powerusers.microsoft.com/t5/Power-Automate-Desktop/PowerAutomate-uninstall-problem/td-p/1224781)
Maybe the fix
`
Problem solved by deleting Microsoft.Flow.RPA.Desktop.UIAutomation.Java.Bridge.Native from the accessibility.properties file @AndrewThompson thanks for giving the hint(API logging)
`
alsow works for you.

**Comment by mmmato** [comment]
Hi @Fruchtzwerg94,

The fix you mentioned works in my case because I don't need that java bridge stuff from Power Automate (but need and use Power Automate Desktop). That's OK for me right now but maybe it would be a good idead for you plugin if you just ignore all the content that is generated before the "<?xml ..." tag. There might be other applications like Power Automate that hook into the java "pipeline(?)".

**Comment by Fruchtzwerg94** [comment]
Hi @mmmato ,

although I think Java itself should always be configured to behave like expected, I've implemented a fix for it. Could you please test the [latest build](https://github.com/Fruchtzwerg94/PlantUmlViewer/actions/runs/4408163838) with the hooks enabled on your system?

BR,
Philipp

**Comment by mmmato** [comment]
Hi.

I re-activated the Power Automate stuff (maybe I need it some day) and tested your build and it works fine for me.

Regards,
Marco

**Comment by Fruchtzwerg94** [comment]
Sounds good. Then I am going to include this in the next release. Thanks for your feedback!

Cheers,
Philipp
